name: Hello, World!
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - name: install lftp
        run: "sudo apt-get install lftp"
      - name: mirror
        run: "lftp -u hysryt,${{ secrets.FTP_PASSWORD }} -e \"mirror --reverse public /home/hysryt/www/laravel;exit\" hysryt.sakura.ne.jp"
