name: Hello, World!
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - name: git ftp push
        run: "git ftp push -u hysryt -p ${{ secrets.FTP_PASSWORD }} --syncroot public -v ftp://hysryt.sakura.ne.jp/www/laravel"
